apiVersion: v1
kind: Service
metadata:
  name:  mockdbservice-svc
  labels:
    app: mockdbservice
spec:
  selector:
    app:  mockdbservice
  type: NodePort
  ports:
   - port:  5000
     nodePort: 30003
     protocol: TCP